<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AsyncMethodResult.proto

namespace GPBMetadata;

class AsyncMethodResult
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
T
AsyncMethodResult.protoDiadoc.Proto"#
AsyncMethodResult
TaskId (	bproto3'
        , true);

        static::$is_initialized = true;
    }
}

