<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CertificateInfo.proto

namespace GPBMetadata;

class CertificateInfo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
x
CertificateInfo.protoDiadoc.Proto"I
CertificateInfo

Thumbprint (	
	ValidFrom (
ValidTo (bproto3'
        , true);

        static::$is_initialized = true;
    }
}

