<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Content.proto

namespace GPBMetadata;

class Content
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
L
Content.protoDiadoc.Proto"%
Content
Size (
Data (bproto3'
        , true);

        static::$is_initialized = true;
    }
}

