<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CustomDataItem.proto

namespace GPBMetadata;

class CustomDataItem
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Z
CustomDataItem.protoDiadoc.Proto",
CustomDataItem
Key (	
Value (	bproto3'
        , true);

        static::$is_initialized = true;
    }
}

