<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ExternalServiceAuthInfo.proto

namespace GPBMetadata;

class ExternalServiceAuthInfo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
{
ExternalServiceAuthInfo.protoDiadoc.Proto"D
ExternalServiceAuthInfo
ServiceUserId (	

Thumbprint (	bproto3'
        , true);

        static::$is_initialized = true;
    }
}

