<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ForwardDocumentEvent.proto

namespace GPBMetadata;

class ForwardDocumentEvent
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Timestamp::initOnce();
        $pool->internalAddGeneratedFile(
            '
‡
ForwardDocumentEvent.protoDiadoc.Proto"S
ForwardDocumentEvent*
	Timestamp (2.Diadoc.Proto.Timestamp
ToBoxId (	bproto3'
        , true);

        static::$is_initialized = true;
    }
}

