<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LoginPassword.proto

namespace GPBMetadata;

class LoginPassword
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
]
LoginPassword.protoDiadoc.Proto"0
LoginPassword
Login (	
Password (	bproto3'
        , true);

        static::$is_initialized = true;
    }
}

