<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RoamingNotification.proto

namespace GPBMetadata;

class RoamingNotification
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
n
RoamingNotification.protoDiadoc.Proto";
RoamingNotification
Success (
Description (	bproto3'
        , true);

        static::$is_initialized = true;
    }
}

