<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Timestamp.proto

namespace GPBMetadata;

class Timestamp
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
C
Timestamp.protoDiadoc.Proto"
	Timestamp
Ticks (bproto3'
        , true);

        static::$is_initialized = true;
    }
}

