<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Invoicing/FnsRegistrationMessageInfo.proto

namespace GPBMetadata\Invoicing;

class FnsRegistrationMessageInfo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
€
*Invoicing/FnsRegistrationMessageInfo.protoDiadoc.Proto.Invoicing"2
FnsRegistrationMessageInfo
Certificates (bproto3'
        , true);

        static::$is_initialized = true;
    }
}

