<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Invoicing/SignatureRejectionInfo.proto

namespace GPBMetadata\Invoicing;

class SignatureRejectionInfo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Invoicing\Signer::initOnce();
        $pool->internalAddGeneratedFile(
            '
¨
&Invoicing/SignatureRejectionInfo.protoDiadoc.Proto.Invoicing"^
SignatureRejectionInfo
ErrorMessage (	.
Signer (2.Diadoc.Proto.Invoicing.Signerbproto3'
        , true);

        static::$is_initialized = true;
    }
}

