<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Docflow/ReceiptDocflow.proto

namespace GPBMetadata\Docflow;

class ReceiptDocflow
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Docflow\Attachment::initOnce();
        $pool->internalAddGeneratedFile(
            '
¥
Docflow/ReceiptDocflow.protoDiadoc.Proto.Docflow"g
ReceiptDocflow

IsFinished (A
ReceiptAttachment (2&.Diadoc.Proto.Docflow.SignedAttachmentbproto3'
        , true);

        static::$is_initialized = true;
    }
}

