<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Docflow/RecipientSignatureRejectionDocflow.proto

namespace GPBMetadata\Docflow;

class RecipientSignatureRejectionDocflow
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Timestamp::initOnce();
        \GPBMetadata\Docflow\Attachment::initOnce();
        $pool->internalAddGeneratedFile(
            '
°
0Docflow/RecipientSignatureRejectionDocflow.protoDiadoc.Proto.DocflowDocflow/Attachment.proto"Ã
"RecipientSignatureRejectionDocflow

IsFinished (U
%RecipientSignatureRejectionAttachment (2&.Diadoc.Proto.Docflow.SignedAttachment2
DeliveryTimestamp (2.Diadoc.Proto.Timestampbproto3'
        , true);

        static::$is_initialized = true;
    }
}

