<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Docflow/ResolutionDocflow.proto

namespace GPBMetadata\Docflow;

class ResolutionDocflow
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
T
Docflow/ResolutionDocflow.protoDiadoc.Proto.Docflow"
ResolutionDocflowbproto3'
        , true);

        static::$is_initialized = true;
    }
}

