<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Documents/DocumentProtocol.proto

namespace GPBMetadata\Documents;

class DocumentProtocol
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
|
 Documents/DocumentProtocol.protoDiadoc.Proto.Documents"8
DocumentProtocol
	PrintForm (
	Signature (bproto3'
        , true);

        static::$is_initialized = true;
    }
}

