<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Documents/DocumentZip.proto

namespace GPBMetadata\Documents;

class DocumentZip
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
x
Documents/DocumentZip.protoDiadoc.Proto.Documents"9
DocumentZipGenerationResult
ZipFileNameOnShelf (	bproto3'
        , true);

        static::$is_initialized = true;
    }
}

