<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetDocumentsV4Request.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Proto.DepartmentFilter</code>
 */
class DepartmentFilter extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string DepartmentId = 1;</code>
     */
    protected $DepartmentId = '';
    /**
     * Generated from protobuf field <code>bool ExcludeSubdepartments = 2;</code>
     */
    protected $ExcludeSubdepartments = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $DepartmentId
     *     @type bool $ExcludeSubdepartments
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GetDocumentsV4Request::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string DepartmentId = 1;</code>
     * @return string
     */
    public function getDepartmentId()
    {
        return $this->DepartmentId;
    }

    /**
     * Generated from protobuf field <code>string DepartmentId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDepartmentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->DepartmentId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool ExcludeSubdepartments = 2;</code>
     * @return bool
     */
    public function getExcludeSubdepartments()
    {
        return $this->ExcludeSubdepartments;
    }

    /**
     * Generated from protobuf field <code>bool ExcludeSubdepartments = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setExcludeSubdepartments($var)
    {
        GPBUtil::checkBool($var);
        $this->ExcludeSubdepartments = $var;

        return $this;
    }

}

