<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetDocumentsV4Request.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Proto.GetDocumentsV4Request</code>
 */
class GetDocumentsV4Request extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string CounteragentBoxIds = 1;</code>
     */
    private $CounteragentBoxIds;
    /**
     * Generated from protobuf field <code>repeated string FromDepartmentIds = 2;</code>
     */
    private $FromDepartmentIds;
    /**
     * Generated from protobuf field <code>repeated string ToDepartmentIds = 3;</code>
     */
    private $ToDepartmentIds;
    /**
     * Generated from protobuf field <code>repeated .Diadoc.Proto.DepartmentFilter Departments = 4;</code>
     */
    private $Departments;
    /**
     * Generated from protobuf field <code>repeated string DocumentTypeNamedIds = 5;</code>
     */
    private $DocumentTypeNamedIds;
    /**
     * Generated from protobuf field <code>string DocumentCategory = 6;</code>
     */
    protected $DocumentCategory = '';
    /**
     * Generated from protobuf field <code>repeated string DocumentStatuses = 7;</code>
     */
    private $DocumentStatuses;
    /**
     * Generated from protobuf field <code>repeated string FileNames = 8;</code>
     */
    private $FileNames;
    /**
     * Generated from protobuf field <code>repeated string DocumentNumbers = 9;</code>
     */
    private $DocumentNumbers;
    /**
     * Generated from protobuf field <code>optional string FromDocumentDate = 10;</code>
     */
    protected $FromDocumentDate = null;
    /**
     * Generated from protobuf field <code>optional string ToDocumentDate = 11;</code>
     */
    protected $ToDocumentDate = null;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Proto.Timestamp FromTimestamp = 12;</code>
     */
    protected $FromTimestamp = null;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Proto.Timestamp ToTimestamp = 13;</code>
     */
    protected $ToTimestamp = null;
    /**
     * Generated from protobuf field <code>repeated string TotalSums = 14;</code>
     */
    private $TotalSums;
    /**
     * Generated from protobuf field <code>optional string ToTotalSum = 15;</code>
     */
    protected $ToTotalSum = null;
    /**
     * Generated from protobuf field <code>optional string FromTotalSum = 16;</code>
     */
    protected $FromTotalSum = null;
    /**
     * Generated from protobuf field <code>repeated .Diadoc.Proto.CustomDataItem CustomData = 17;</code>
     */
    private $CustomData;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Proto.SortDirection SortDirection = 18;</code>
     */
    protected $SortDirection = null;
    /**
     * Generated from protobuf field <code>optional int32 Count = 19;</code>
     */
    protected $Count = null;
    /**
     * Generated from protobuf field <code>optional string AfterIndexKey = 20;</code>
     */
    protected $AfterIndexKey = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $CounteragentBoxIds
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $FromDepartmentIds
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $ToDepartmentIds
     *     @type array<\Diadoc\Proto\DepartmentFilter>|\Google\Protobuf\Internal\RepeatedField $Departments
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $DocumentTypeNamedIds
     *     @type string $DocumentCategory
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $DocumentStatuses
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $FileNames
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $DocumentNumbers
     *     @type string $FromDocumentDate
     *     @type string $ToDocumentDate
     *     @type \Diadoc\Proto\Timestamp $FromTimestamp
     *     @type \Diadoc\Proto\Timestamp $ToTimestamp
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $TotalSums
     *     @type string $ToTotalSum
     *     @type string $FromTotalSum
     *     @type array<\Diadoc\Proto\CustomDataItem>|\Google\Protobuf\Internal\RepeatedField $CustomData
     *     @type int $SortDirection
     *     @type int $Count
     *     @type string $AfterIndexKey
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GetDocumentsV4Request::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string CounteragentBoxIds = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCounteragentBoxIds()
    {
        return $this->CounteragentBoxIds;
    }

    /**
     * Generated from protobuf field <code>repeated string CounteragentBoxIds = 1;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCounteragentBoxIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->CounteragentBoxIds = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string FromDepartmentIds = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFromDepartmentIds()
    {
        return $this->FromDepartmentIds;
    }

    /**
     * Generated from protobuf field <code>repeated string FromDepartmentIds = 2;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFromDepartmentIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->FromDepartmentIds = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string ToDepartmentIds = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getToDepartmentIds()
    {
        return $this->ToDepartmentIds;
    }

    /**
     * Generated from protobuf field <code>repeated string ToDepartmentIds = 3;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setToDepartmentIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->ToDepartmentIds = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Proto.DepartmentFilter Departments = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDepartments()
    {
        return $this->Departments;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Proto.DepartmentFilter Departments = 4;</code>
     * @param array<\Diadoc\Proto\DepartmentFilter>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDepartments($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Proto\DepartmentFilter::class);
        $this->Departments = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string DocumentTypeNamedIds = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDocumentTypeNamedIds()
    {
        return $this->DocumentTypeNamedIds;
    }

    /**
     * Generated from protobuf field <code>repeated string DocumentTypeNamedIds = 5;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDocumentTypeNamedIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->DocumentTypeNamedIds = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string DocumentCategory = 6;</code>
     * @return string
     */
    public function getDocumentCategory()
    {
        return $this->DocumentCategory;
    }

    /**
     * Generated from protobuf field <code>string DocumentCategory = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setDocumentCategory($var)
    {
        GPBUtil::checkString($var, True);
        $this->DocumentCategory = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string DocumentStatuses = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDocumentStatuses()
    {
        return $this->DocumentStatuses;
    }

    /**
     * Generated from protobuf field <code>repeated string DocumentStatuses = 7;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDocumentStatuses($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->DocumentStatuses = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string FileNames = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFileNames()
    {
        return $this->FileNames;
    }

    /**
     * Generated from protobuf field <code>repeated string FileNames = 8;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFileNames($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->FileNames = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string DocumentNumbers = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDocumentNumbers()
    {
        return $this->DocumentNumbers;
    }

    /**
     * Generated from protobuf field <code>repeated string DocumentNumbers = 9;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDocumentNumbers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->DocumentNumbers = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string FromDocumentDate = 10;</code>
     * @return string
     */
    public function getFromDocumentDate()
    {
        return isset($this->FromDocumentDate) ? $this->FromDocumentDate : '';
    }

    public function hasFromDocumentDate()
    {
        return isset($this->FromDocumentDate);
    }

    public function clearFromDocumentDate()
    {
        unset($this->FromDocumentDate);
    }

    /**
     * Generated from protobuf field <code>optional string FromDocumentDate = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setFromDocumentDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->FromDocumentDate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string ToDocumentDate = 11;</code>
     * @return string
     */
    public function getToDocumentDate()
    {
        return isset($this->ToDocumentDate) ? $this->ToDocumentDate : '';
    }

    public function hasToDocumentDate()
    {
        return isset($this->ToDocumentDate);
    }

    public function clearToDocumentDate()
    {
        unset($this->ToDocumentDate);
    }

    /**
     * Generated from protobuf field <code>optional string ToDocumentDate = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setToDocumentDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->ToDocumentDate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Proto.Timestamp FromTimestamp = 12;</code>
     * @return \Diadoc\Proto\Timestamp|null
     */
    public function getFromTimestamp()
    {
        return $this->FromTimestamp;
    }

    public function hasFromTimestamp()
    {
        return isset($this->FromTimestamp);
    }

    public function clearFromTimestamp()
    {
        unset($this->FromTimestamp);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Proto.Timestamp FromTimestamp = 12;</code>
     * @param \Diadoc\Proto\Timestamp $var
     * @return $this
     */
    public function setFromTimestamp($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\Timestamp::class);
        $this->FromTimestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Proto.Timestamp ToTimestamp = 13;</code>
     * @return \Diadoc\Proto\Timestamp|null
     */
    public function getToTimestamp()
    {
        return $this->ToTimestamp;
    }

    public function hasToTimestamp()
    {
        return isset($this->ToTimestamp);
    }

    public function clearToTimestamp()
    {
        unset($this->ToTimestamp);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Proto.Timestamp ToTimestamp = 13;</code>
     * @param \Diadoc\Proto\Timestamp $var
     * @return $this
     */
    public function setToTimestamp($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\Timestamp::class);
        $this->ToTimestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string TotalSums = 14;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTotalSums()
    {
        return $this->TotalSums;
    }

    /**
     * Generated from protobuf field <code>repeated string TotalSums = 14;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTotalSums($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->TotalSums = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string ToTotalSum = 15;</code>
     * @return string
     */
    public function getToTotalSum()
    {
        return isset($this->ToTotalSum) ? $this->ToTotalSum : '';
    }

    public function hasToTotalSum()
    {
        return isset($this->ToTotalSum);
    }

    public function clearToTotalSum()
    {
        unset($this->ToTotalSum);
    }

    /**
     * Generated from protobuf field <code>optional string ToTotalSum = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setToTotalSum($var)
    {
        GPBUtil::checkString($var, True);
        $this->ToTotalSum = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string FromTotalSum = 16;</code>
     * @return string
     */
    public function getFromTotalSum()
    {
        return isset($this->FromTotalSum) ? $this->FromTotalSum : '';
    }

    public function hasFromTotalSum()
    {
        return isset($this->FromTotalSum);
    }

    public function clearFromTotalSum()
    {
        unset($this->FromTotalSum);
    }

    /**
     * Generated from protobuf field <code>optional string FromTotalSum = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setFromTotalSum($var)
    {
        GPBUtil::checkString($var, True);
        $this->FromTotalSum = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Proto.CustomDataItem CustomData = 17;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCustomData()
    {
        return $this->CustomData;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Proto.CustomDataItem CustomData = 17;</code>
     * @param array<\Diadoc\Proto\CustomDataItem>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCustomData($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Proto\CustomDataItem::class);
        $this->CustomData = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Proto.SortDirection SortDirection = 18;</code>
     * @return int
     */
    public function getSortDirection()
    {
        return isset($this->SortDirection) ? $this->SortDirection : 0;
    }

    public function hasSortDirection()
    {
        return isset($this->SortDirection);
    }

    public function clearSortDirection()
    {
        unset($this->SortDirection);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Proto.SortDirection SortDirection = 18;</code>
     * @param int $var
     * @return $this
     */
    public function setSortDirection($var)
    {
        GPBUtil::checkEnum($var, \Diadoc\Proto\SortDirection::class);
        $this->SortDirection = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 Count = 19;</code>
     * @return int
     */
    public function getCount()
    {
        return isset($this->Count) ? $this->Count : 0;
    }

    public function hasCount()
    {
        return isset($this->Count);
    }

    public function clearCount()
    {
        unset($this->Count);
    }

    /**
     * Generated from protobuf field <code>optional int32 Count = 19;</code>
     * @param int $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->Count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string AfterIndexKey = 20;</code>
     * @return string
     */
    public function getAfterIndexKey()
    {
        return isset($this->AfterIndexKey) ? $this->AfterIndexKey : '';
    }

    public function hasAfterIndexKey()
    {
        return isset($this->AfterIndexKey);
    }

    public function clearAfterIndexKey()
    {
        unset($this->AfterIndexKey);
    }

    /**
     * Generated from protobuf field <code>optional string AfterIndexKey = 20;</code>
     * @param string $var
     * @return $this
     */
    public function setAfterIndexKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->AfterIndexKey = $var;

        return $this;
    }

}

